name: Build Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk unzip zip
          pip3 install --upgrade pip
          pip3 install buildozer cython
      - name: Install Android command line tools
        run: |
          sudo apt-get install -y wget
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;21.4.7075529"
      - name: Build APK
        env:
          ANDROID_SDK_ROOT: ${{ runner.home }}/android-sdk
        run: |
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: AnimeXstream-apk
          path: bin/*.apk
